White labelling updates
Budibase/budibase pull request #10093
Opened 2023-03-21 15:13 UTC by deanhannigan

## Description

Adding a new branding section to the portal to centralise the new white labelling features in Budibase.

- Logo - This feature has been moved from the organisation page
  - `Self Host - Business` - Visible in the portal header, the app navigation and log in page.
  - `Cloud - Pro` - Visible in the portal header and the app navigation.
- Favicon -
  - `Self Host - Business` - Visible in published apps and on the auth screens.
  - `Cloud - Pro` - Visible for published apps
- Login Page - `Self Host - Business`
  - Page Title - The main tab/window title.
  - Login title - The text immediately below the branding 
  - Login button text - currently `Log in to Budibase`
  - Show/Hide testimonials
  - Show/Hide license agreement
- Email Branding - A Budibase branded header has been added to **all** outgoing emails.
   - ![Screenshot 2023-03-21 at 10 56 00](https://user-images.githubusercontent.com/5913006/226632842-13323aab-0dff-4c4f-996a-6afd03808aa6.png)
   - This can be removed in `Self Host - Business` and `Cloud - Pro`
- Customisable app preview meta tags - used when sharing your app URLs online!
  - `Self Host - Business` and `Cloud - Pro`
  - Image Url - `Twitter` and `Open Graph` supported. A configurable image that will display along with your application card. If this not set, the default "Built with budibase" card will show instead.
   - Title - Apps will render with their own individual titles by default e.g `My first app - built with Budibase` or you can you this value to act as a global override.
   - Description - add some additional text to your app previews.

- Added a new, low profile File component.

Addresses: 
- BUDI-6430

## Screenshots

New Branding section in the portal

<img src="https://user-images.githubusercontent.com/5913006/226640688-9646d357-3e73-4cff-9867-259b75619f48.png" width="500"/>

`Self host` login page with custom favicon, page title and main branding. Testimonials have also been disabled.

<img src="https://user-images.githubusercontent.com/5913006/226642490-76c2aa28-e5b9-4cb0-9fcb-d181a62cbe16.png" width="500"/>

Custom branding will now appear in the app by default.

<img src="https://user-images.githubusercontent.com/5913006/226639975-627e98f9-ebde-4a21-8def-8a1e4b6a17ca.png" width="500"/>

Application Preview options. 

<img src="https://user-images.githubusercontent.com/5913006/226644917-779a2a0c-659b-4a53-9d77-281047c415d8.png" width="500"/>

Metadata cards. How they currently look when shared on twitter.

<img src="https://user-images.githubusercontent.com/5913006/226647636-ba25c05c-2089-49b8-b6f1-b7054e711d63.png" width="500"/>

More incoming

2023-03-27 09:15 UTC, Rory-Powell requested changes
I think we should use a licensed feature flag instead, left a comment with more details

2023-03-27 10:00 UTC, deanhannigan commented on packages/builder/src/pages/builder/portal/settings/branding.svelte
> +  $: selfhostPremium = $licensing.isEnterprisePlan || $licensing.isBusinessPlan
Yep, I see what your getting at. I'll make the change now. Cheers! :thumbsup:

2023-03-27 16:37 UTC, shogunpurple commented on packages/worker/src/api/controllers/global/configs.ts
> +    const licensedConfig: any = {}
```js 

let licensedConfig: object = {}

if (!license || license?.features.includes(Feature.BRANDING)) {
      licensedConfig = {
         emailBrandingEnabled: true,
         testimonialsEnabled: true,
         platformTitle: undefined,
         metaDescription: undefined,
         metaImageUrl: undefined,
         metaTitle: undefined,
      }
    }
```

2023-03-27 16:41 UTC, shogunpurple commented on packages/worker/src/utilities/email.ts
> +  let core = EmailTemplates.core
constants are usually Pascal or screaming snake - `Core` or `CORE`

2023-03-27 20:23 UTC, Rory-Powell commented on packages/worker/src/api/controllers/global/configs.ts
> +    const license = await licensing.getLicense()
Should use:

```ts
licensing.cache.getCachedLicense()
```

The `getLicense` will go to account portal and fetch the license from stripe, where are the above will use the local cache and populate if needed.

2023-03-27 20:27 UTC, Rory-Powell commented on packages/worker/src/api/controllers/global/configs.ts
> +    if (!license || license?.features.indexOf(Feature.BRANDING) == -1) {
You can instead use:

```ts
import { features } from "@budibase.pro"
if (!(await features.isFeatureEnabled(Feature.BRANDING)))
```

or you can add a helper to here:
https://github.com/Budibase/budibase-pro/blob/develop/packages/pro/src/sdk/features/features.ts
similar to `isBackupsEnabled`

```ts
export function isBrandingEnabled() {
   return isFeatureEnabled(Feature.BRANDING)
}
```

2023-03-27 20:27 UTC, Rory-Powell commented on packages/worker/src/api/controllers/global/configs.ts
> +    if (!license || license?.features.indexOf(Feature.BRANDING) == -1) {
Under the hood this will load the cached license, so will be able to remove the manual license retrieval from above

2023-03-27 20:30 UTC, Rory-Powell commented
Could you post a screenshot of the branding page when the feature is not available in the license?

2023-03-27 20:34 UTC, deanhannigan commented
@Rory-Powell this is from my local instance in self mode and a pro license

<img src ="https://user-images.githubusercontent.com/5913006/228059724-df0b5aaa-d0e0-4588-9cb4-be8ef1593aff.png">

2023-03-27 21:22 UTC, Rory-Powell commented on packages/worker/src/api/controllers/global/configs.ts
> +    if (!license || license?.features.indexOf(Feature.BRANDING) == -1) {
Nice!

2023-03-27 21:36 UTC, Rory-Powell commented
Created a suggested change to how we access branding properties here: 
- https://github.com/Budibase/budibase-pro/pull/149
- https://github.com/Budibase/budibase/pull/10127

2023-03-28 08:08 UTC, aptkingston approved these changes
Super work Dean. Couple of very minor changes suggested but no blockers. Looks good from my perspective, so I'm happy for you to merge whenever you've got those other changes with Rory and the pro bundle sorted.

2023-03-28 13:26 UTC, merged