Post Sign Up Onboarding Changes
Budibase/budibase pull request #10701
Opened 2023-05-25 15:34 UTC by Ghrehh

## Description
- Removes the data portion of the existing onboarding experience, instead pushing users directly to the new data creation screen.
- Users can now add sample data to existing apps.
- Use the new data screen instead of the existing modal for creating new data sources.
- The last onboarding step will now deposit the user back on the new data screen

Addresses: 
https://linear.app/budibase/issue/BUDI-6949/adapt-post-sign-up-flow
https://linear.app/budibase/issue/BUDI-6931/remove-data-source-modal-and-add-empty-state-for-data-source-page

## Screenshots
|New Page|New Page With Datasource Modal|New Page with Close Button|
|---|---|---|
|<img width="1194" alt="Screenshot 2023-05-25 at 16 14 51" src="https://github.com/Budibase/budibase/assets/12501626/fe3321bf-5788-46cc-85c4-b0a54ad223fc">|<img width="1187" alt="Screenshot 2023-05-25 at 16 14 58" src="https://github.com/Budibase/budibase/assets/12501626/2502083b-599a-40f9-932e-7435823cc43e">|<img width="1192" alt="Screenshot 2023-05-25 at 16 15 10" src="https://github.com/Budibase/budibase/assets/12501626/d9e7dfbd-739a-4e88-83a5-eb7071cd9765">|

2023-05-25 15:46 UTC, deanhannigan commented on packages/builder/src/components/backend/DatasourceNavigator/modals/GoogleDatasourceConfigModal.svelte
If you leave out the variable `onCancel` entirely, won't it achieve the same result? If it's undefined, it does nothing anyway.

2023-05-25 18:39 UTC, melohagan commented
Looks awesome! Just wondering if there could be any sorting or grouping added. The datasources don't seem to presented in any particular order in the screenshots.

2023-05-26 10:38 UTC, Ghrehh commented on packages/builder/src/components/backend/DatasourceNavigator/modals/GoogleDatasourceConfigModal.svelte
Doh, good catch.

2023-05-26 11:01 UTC, Ghrehh commented
@melohagan Good point! I've copied the existing sorting code now, so it should be the same sorting as it was previously.

2023-05-26 15:33 UTC, aptkingston requested changes
I haven't been through the code yet, but I pulled this down to try it and ran into a few issues straight away:

- The colours are static and don't respect the users theme
![image](https://github.com/Budibase/budibase/assets/9075550/76a2c801-34b1-4fb2-af21-f79f5063803d)
- ~~Oracle DB is missing~~ (edit - this is just my env)
- There should be 4 columns of datasources rather than unlimited. You can check the figma for reference
- Clicking on any external datasource throws an error and does nothing
![image](https://github.com/Budibase/budibase/assets/9075550/5809b76f-0b53-4460-a570-5b6746c75efa)
- When hovering over a datasource, the cursor flips between the default cursor and `pointer` multiple times. This should consistently be `pointer`
- The notification when creating a table says "table foo created"
![image](https://github.com/Budibase/budibase/assets/9075550/daddf7a3-2bac-49fd-9249-4515583085c9)

Let's get those sorted first and then I'll review the code 👍

2023-05-26 16:27 UTC, Ghrehh commented
@aptkingston Ah, my bad particularly on the external data sources not working, but update when implementing sorting.

All your feedback should be sorted now.

2023-05-30 07:49 UTC, aptkingston approved these changes
Code LGTM! Just those few other changes mentioned in my previous comment from manual testing, then should be good to go 👍

2023-05-30 10:44 UTC, deanhannigan approved these changes
LGTM! This looks fantastic!

2023-05-30 10:49 UTC, Ghrehh commented
@aptkingston Should be good to review again if you want to have a gander

2023-05-30 11:54 UTC, merged