Add camera choice option to QR scanner field
Budibase/budibase pull request #12109
Opened 2023-10-18 15:17 UTC by zedascouves

## Description
_Allows selecting the camera for the QR scanner field. Issue https://github.com/Budibase/budibase/issues/11459._

Addresses: 
- `https://github.com/Budibase/budibase/issues/11459`

## Documentation
- [X] I have reviewed the budibase documentatation to verify if this feature requires any changes. If changes or new docs are required I have written them.

2023-10-19 07:28 UTC, aptkingston approved these changes
Looks good to me! Thanks for the contribution @zedascouves.

2023-10-20 11:43 UTC, aptkingston requested changes

2023-10-20 11:43 UTC, aptkingston commented on packages/client/src/components/app/forms/CodeScanner.svelte
> +  let cameraSetting = { facingMode: {preferredCamera} }
This is now an object and won't work - we just want a string.

This needs to be:
```js
let cameraSetting = { facingMode: preferredCamera }
```

2023-10-20 11:47 UTC, zedascouves reviewed
I've changed the code as suggested.

2023-10-20 13:16 UTC, aptkingston approved these changes

2023-10-27 09:08 UTC, zedascouves commented
Do I need to do anything else for this to be successfully merged?

2023-11-06 18:02 UTC, merged