Added selected class to data provider options.
Budibase/budibase pull request #12196
Opened 2023-10-27 10:03 UTC by ConorWebb96

## Description
When lots of data providers/queries/views are on a page. Its very difficult to see what is currently selected in the list. This highlights whatever is selected in blue.

Addresses: 
- [Source query highlight at Provider data dropdown stopped working](https://github.com/Budibase/budibase/discussions/12132)

## Screenshots
<img width="221" alt="Screenshot 2023-10-27 at 11 01 51" src="https://github.com/Budibase/budibase/assets/126772285/1ddab9db-e5c7-4645-ab16-d4ae34f6f1bb">
<img width="162" alt="Screenshot 2023-10-27 at 11 02 21" src="https://github.com/Budibase/budibase/assets/126772285/70389a38-5bb2-4cbc-8406-d6745c81cd1f">

## Documentation
- [x] I have reviewed the Budibase documentation to verify if this feature requires any changes. If changes or new docs are required I have written them.

2023-10-27 13:59 UTC, deanhannigan requested changes
Hey Conor, the code changes look great but would it be possible to change the design to be more in line with other selects in the builder? Typically there is a small tick to indicate the current selection.
 
Something like the `Edit Column` modal in the data section:

<img width="395" alt="Screenshot 2023-10-27 at 14 48 44" src="https://github.com/Budibase/budibase/assets/5913006/50c11750-c4f2-433d-b218-e44787708e13">

2023-10-27 14:59 UTC, aptkingston commented
The main reason I haven't implemented this before is that we don't actually have a consistent way to identify a given datasource - they all have different properties. This PR uses the label, but that would mean that if you had a table named `Foo`, and a query named `Foo` then they would both be marked as selected.

The only real way to tell is compare both the type and identification property of each datasource against each other. You can't even just do a deep compare because schema etc may have changed. So that means comparing `_id` for tables, `id` for view V2s, `providerId` for data providers etc. It's quite a lot of conditional checks.

The easier approach is probably add some sort of new `key` property to all options, and use this going forward to determine what's selected, just accepting that existing values will not be marked as selected until they are changed once more.

2023-10-30 10:04 UTC, ConorWebb96 commented
Thanks for the feedback @deanhannigan,

How does this look?
<img width="306" alt="Screenshot 2023-10-30 at 10 03 49" src="https://github.com/Budibase/budibase/assets/126772285/cd7a1740-dddc-482f-8d48-854a425cee09">

2023-10-30 10:27 UTC, deanhannigan approved these changes

2023-10-31 11:32 UTC, aptkingston approved these changes

2023-10-31 11:34 UTC, aptkingston commented
There's a lot of duplicated boilerplate code now to enable the tick icon, which would be much nicer pulled out into a separate component, but I don't mind merging this anyway.

2023-10-31 15:01 UTC, aptkingston reviewed
Nice @ConorWebb96 - much cleaner!

Not a blocker, but the cleaner way to structure these files would be create a folder `DataSourceSelect`, then put both the existing `DataSourceSelect.svelte` inside that, and also this new component `SelectItem.svelte`. I'd also call the component something like `DataSourceCategory` 👌

2023-11-01 09:38 UTC, ConorWebb96 commented on packages/builder/src/components/design/settings/controls/DataSourceSelectItem/SelectItem.svelte
> +      on:keydown={e => {
Fixed thanks for the feedback.

2023-11-02 08:49 UTC, aptkingston commented
Looks nearly ready to go @ConorWebb96 👍 Tested this in the feature branch and just noticed a small style issue - the options don't use the full width of the popover (notice the grey at the right side edge):
![image](https://github.com/Budibase/budibase/assets/9075550/10d090e1-d42f-4f70-ac7f-d6b9826f45de)

Completely not a blocker but could we also name the folder just `DataSourceSelect` instead of `DataSourceSelectItem`? That's the pattern we normally use.

2023-11-02 14:25 UTC, merged