Allow Collapsing Selected Components, Add Hotkeys for Collapsing Components
Budibase/budibase pull request #12764
Opened 2024-01-11 16:30 UTC by Ghrehh

## Description
- Allow collapsing components, even those that the user is currently selecting. If the user selects a component contained within a collapsed parent via the app preview, that component will be temporarily visible in the tree.
- Add hotkeys and help menu options for collapsing, expanding and recursively collapsing and expanding components.
- Persists collapsed components in session storage, so that collapsed components are at least temporarily maintained if the user for instance navigates between the data and design sections.

## Addresses
- https://linear.app/budibase/issue/BUDI-7675/design-section-component-tree-dont-expand-all-components

2024-01-12 11:03 UTC, deanhannigan requested changes
LGTM! Minor issue with the tree node selection but the feature works nicely when navigating around the builder 👍

2024-01-17 11:07 UTC, Ghrehh commented on packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/ComponentDropdownMenu.svelte
> +  {#if component._children.length > 0}
Good catch, should be fixed now.

2024-01-25 12:09 UTC, deanhannigan approved these changes
LGTM!

2024-02-09 11:46 UTC, Ghrehh commented
Note: We had an issue where the order of the `:fix` version of our lint script was in a different order than the non-fix version, which lead to a weird intermittent failure here, should be fixed now.

2024-02-15 10:53 UTC, merged