Plumbing for showing a maintenance page when SQS is required but missing.
Budibase/budibase pull request #12914
Opened 2024-01-30 17:36 UTC by samwho

## Description

This PR adds a check for the new `maintanence` property on the call to `/api/system/environment` (was previously `infrastructure.sqs` but I generalised it a little) and if it finds it to be not empty, redirects to a page that blocks the user and forces them to perform the required maintenance.

I haven't yet written the documentation for the SQS migration, but the page will link to it when I have. For the time being, it's impossible to trigger this redirect unless `sqsRequired` has been set in the code.

Looking for feedback on:

- Approach taken to redirect the user. I'm trying to not introduce any more overhead to the page (I don't want to make any extra calls to `/api/system/environment`) while capturing the largest percentage of users in the builder.
- I decided against redirecting users of apps because I suspect there's nothing they'll be able to do about it anyway. If we did want to show them a blocking screen, I imagine it would need different contents to the one shown in the builder. What do you think?
- Visual appearance of the page. I am bad at this, and it currently doesn't look good 🙈 Halp.

## Addresses
- https://linear.app/budibase/issue/BUDI-7664/sqs-self-host-ui-for-detecting-lack-of-sqs-support

## Screenshots

![CleanShot 2024-01-30 at 17 31 33@2x](https://github.com/Budibase/budibase/assets/338027/50573193-73a1-43c3-a944-0c98a2d16364)

2024-01-31 12:16 UTC, aptkingston reviewed
LGTM other than one potential issue when not running self-hosted. I'll give Andy a shout to do a quick mockup of how we could style the error page.

As for end-user apps, I think it depends on whether their apps will be functional or not. If their apps will be broken when in this state, then I think we do need to redirect them to some sort of error page, with different copy than the one for builders.

2024-02-02 16:24 UTC, aptkingston commented
In terms of page design, Andy thought to just follow what we have for the other error pages - like the 502 one here (error.html):
<img width="1164" alt="image" src="https://github.com/Budibase/budibase/assets/9075550/890bf0b9-4f1e-4244-91da-b2fd798527e9">

May need to make it slightly wider for the additional copy though! I'd keep the copy as terse as possible too 👌

2024-02-21 11:06 UTC, samwho commented
I've restyled the page and updated the screenshots in the PR description @aptkingston. Let me know what you think!

@mike12345567 I can't remember where we landed re: a separate maintenance page for users. I imagine that installations that get into the state where this maintenance page shows will be failing most screens, should we show a user-specific maintenance page asking them to contact the Budibase admin or some such?

We also need to write a CouchDB migration guide. Right now I'm just linking to the docs homepage as a placeholder. I'll work on some docs for this, though I imagine it's not possible to complete them just because e.g. for Helm the guidance is going to be to update to a specific Helm chart version, which we haven't published yet so we don't know what version.

2024-02-26 09:49 UTC, mike12345567 commented on packages/builder/src/pages/builder/maintenance/index.svelte
> +    margin-top: 15px;
generally when it comes to stuff like padding/margin, we try top use the `var(--spacing-{size})` variables just to try and keep spacing consistent.

2024-02-26 09:53 UTC, mike12345567 approved these changes
LGTM - one NAB comment!

2024-02-26 09:54 UTC, mike12345567 commented
> I've restyled the page and updated the screenshots in the PR description @aptkingston. Let me know what you think!
> 
> @mike12345567 I can't remember where we landed re: a separate maintenance page for users. I imagine that installations that get into the state where this maintenance page shows will be failing most screens, should we show a user-specific maintenance page asking them to contact the Budibase admin or some such?
> 
> We also need to write a CouchDB migration guide. Right now I'm just linking to the docs homepage as a placeholder. I'll work on some docs for this, though I imagine it's not possible to complete them just because e.g. for Helm the guidance is going to be to update to a specific Helm chart version, which we haven't published yet so we don't know what version.

On the question of a separate page for users - not quite sure what you mean - do you mean when they load a client app?

2024-02-26 10:02 UTC, samwho commented
> On the question of a separate page for users - not quite sure what you mean - do you mean when they load a client app?

When a builder tries to go somewhere and we determine that they need to upgrade to SQS, we show a page that links to the docs to do that. This page wouldn't be appropriate to show a normal user of the app.

What they will see today is, very likely, a completely broken app. Do we want to instead show them a nicer "this Budibase installation is not configured correctly, contact your administrator to let them know" screen or some such?

2024-02-26 11:00 UTC, mike12345567 commented
> > On the question of a separate page for users - not quite sure what you mean - do you mean when they load a client app?
> 
> When a builder tries to go somewhere and we determine that they need to upgrade to SQS, we show a page that links to the docs to do that. This page wouldn't be appropriate to show a normal user of the app.
> 
> What they will see today is, very likely, a completely broken app. Do we want to instead show them a nicer "this Budibase installation is not configured correctly, contact your administrator to let them know" screen or some such?

Ah yes I understand what you mean - yeah I think we should build a similar check into the client library as well, but just say to contact the administrator to get the installation updated correctly.

2024-02-26 11:25 UTC, aptkingston requested changes
I think I misunderstood our conversation about whether we should use raw HTML or components - I thought this page was going to be a HTML file, like the "Houston we have a problem" page, rather than a svelte file. That's my bad.

Since this page is svelte and within the main frontend bundle, we should definitely use BBUI components here where possible. I've added in the replacements as comments. Swapping out the raw HTML for BBUI components will also improve the sizing of some of these components, which would be my only other comment. The HTML for layout is totally fine - I just specifically mean using BBUI components for the text elements and button.

Code and logic all looks good though

I'll also ping Andy once these changes are made, to sign off on the final design.

2024-02-26 11:25 UTC, aptkingston commented on packages/builder/src/pages/builder/maintenance/index.svelte
> +          <h1 class="title">Please upgrade your Budibase installation</h1>
We should replace this with the BBUI `Heading` component.

2024-02-26 11:25 UTC, aptkingston commented on packages/builder/src/pages/builder/maintenance/index.svelte
> +          <p>
We should replace these with BBUI `Body` components.

2024-02-26 11:25 UTC, aptkingston commented on packages/builder/src/pages/builder/maintenance/index.svelte
> +          <div class="buttons">
We should replace this with the BBUI `Button` component.

2024-02-26 11:25 UTC, aptkingston commented on packages/builder/src/pages/builder/maintenance/index.svelte
> +  }
We don't need to worry about adding these styles - we'll already have them loaded into scope.

2024-02-26 11:25 UTC, aptkingston commented on packages/builder/src/pages/builder/maintenance/index.svelte
> +  }
We can remove a lot of these styles when we swap to BBUI components, as they're all pre-styled.

2024-03-14 14:38 UTC, aptkingston approved these changes
LGTM!

One thing to keep in mind is that older client libraries don't contain this code, so if there was maintenance running then users of old apps wouldn't know about it.

There's no easy solution to that I don't think. You'd have to either:
- Prevent maintenance if you have outdated apps
- Forcefully update all apps to the latest

I don't think either of those are feasible, so we'll just have to accept that outdated apps will just break without an explanation.

2024-03-14 14:53 UTC, merged