Joe's lab day minor updates
Budibase/budibase pull request #12944
Opened 2024-02-02 13:39 UTC by joebudi

## Description
Minor UI/UX changes. @AndyWhann may want to review one change (col/row icons):
![CleanShot 2024-02-02 at 13 37 10@2x](https://github.com/Budibase/budibase/assets/49767913/201038e6-415a-42bd-b44a-ff2e8454d77b)

## Addresses
- My pet peeves

2024-02-09 11:17 UTC, melohagan requested changes
A couple of icons that need updated for consistency, but otherwise looks good!

2024-02-09 13:52 UTC, joebudi commented on packages/client/manifest.json
> +            "barIcon": "TableSelectColumn",
I wasn't sure about the icons I picked, but the current ones always confuse me. I could be alone on this.

2024-02-21 09:32 UTC, joebudi commented on packages/client/manifest.json
> +            "barIcon": "TableSelectColumn",
I spoke with @AndyWhann Mel. We will go with the icons above until there are better "arrow icons" with the Spectrum 2 release. I've also [asked for a preview of the new icon set.](https://github.com/adobe/spectrum-css/discussions/2549)

2024-02-21 11:37 UTC, melohagan approved these changes

2024-02-21 13:28 UTC, merged