Fix for custom branding not appearing on login
Budibase/budibase pull request #13004
Opened 2024-02-09 15:58 UTC by PClmnt

## Description
Fixes an issue where custom branding wasn't being showing for users. Talked about a cookie related fix for this in Discord, but upon further discussion with Dean this fix seems to be a lot more simple. Essentially if the branding exists for a user, then don't redirect to account portal and just stay at the 'Budibase' login screen with associated custom branding. 
## Addresses
[BUDI-7962
](https://linear.app/budibase/issue/BUDI-7962/allow-custom-login-to-be-show-as-default-for-cloud-when-a-premium-user)

2024-02-09 16:33 UTC, mike12345567 approved these changes

2024-02-09 20:29 UTC, melohagan requested changes

2024-02-09 20:29 UTC, melohagan commented on packages/builder/src/pages/builder/auth/_layout.svelte
> +    !$admin.checklist.branding
This makes me nervous. Should it be `$admin?.checklist?.branding` like the line above, or is the line above incorrect?

2024-02-12 09:19 UTC, PClmnt commented
The more I thought about this, the more I think it's missing something. I talked with @deanhannigan  on Friday and we agreed this is the best approach. But in this case, if a user doesn't have their own custom SSO setup they won't be able to use it at all? i.e I think what [BUDI-7962
](https://linear.app/budibase/issue/BUDI-7962/allow-custom-login-to-be-show-as-default-for-cloud-when-a-premium-user)
 should really be is a ticket so support the use of branding on the account portal login page. Because this way users that were previously able to login via Microsoft or Google will not be able to when branding is set, without configuring custom SSO

2024-02-13 16:05 UTC, mike12345567 commented on packages/builder/src/pages/builder/auth/_layout.svelte
> +    console.log(domain)
Extra console log! Not sure why this wasn't caught by linter

2024-02-13 16:05 UTC, mike12345567 approved these changes
LGTM - one console log needing removed.

2024-02-14 10:31 UTC, melohagan approved these changes

2024-02-14 10:32 UTC, merged