App list actions
Budibase/budibase pull request #13116
Opened 2024-02-22 15:59 UTC by deanhannigan

## Description

Adds in a new context menu, allowing you to perform some of the handiest app actions straight from the app list screen.

- `Duplicate App` is a new app action that makes a new application from the selected app. This will copy the entire contents of the current dev application including any internal datasource rows and/or attachments.
- `Export lasted edited app` - will export the app with any unpublished changes
- `Export lasted published app` - will only export the currently published version of the application *if* it's available
- `Delete` will prompt users to re-enter their application name and delete their applications. A general update was made to the modal so that you can now click on the app name to automatically populate the confirmation field.

## Addresses
- https://linear.app/budibase/issue/BUDI-7677/apps-list-add-more-options-to-the-apps-list

## Screenshots
Access the available `Duplicate`, `Delete` and `Export` options in the app list context menu.

![Screenshot 2024-02-21 at 15 35 06](https://github.com/Budibase/budibase/assets/5913006/921d3b1d-ca32-4199-93bc-08bbedc97680)

The new duplicate app menu. Enforces the same rules used when creating new applications: no duplicate names or app urls.

<img src="https://github.com/Budibase/budibase/assets/5913006/c12e51ab-5f2f-45ec-87b9-5b4ce745b9a3" width="400"/>

The delete menu has been updated to allow users to click on the app name to populate the text field. Should shave of those valuable seconds.

<img src="https://github.com/Budibase/budibase/assets/5913006/4b85e380-3dde-4235-a122-d344b88f6dc0" width="400"/>

2024-03-04 15:13 UTC, aptkingston requested changes
NAB but there's a space after the clickable app name here, before the question mark:
![image](https://github.com/Budibase/budibase/assets/9075550/6e01eae2-7b25-462e-890e-7941b6c1701a)

Important change needed:
If you're a creator (so have access to the portal) but only have user level access to someone elses app, you will currently still see the context menu for that app in the side nav, when you shouldn't:
![image](https://github.com/Budibase/budibase/assets/9075550/686cdd3b-77d1-4ad2-8721-b9e787a3cbd7)
The main app list handles this correctly, and hides the context menu and edit button, at least when the app is unpublished. The feature branch got nuked before I could check with a published app.

Everything works perfectly though, so great job!

2024-03-04 15:33 UTC, samwho commented on packages/server/src/api/controllers/application.ts
> +  await create(createReq)
`create` could have its signature changed to `create(ctx: UserCtx<CreateAppRequest, App>)` and then that could flow into here to get rid of the `any` above. In general we're trying not to add any new `any`s into the backend code unless they're unavoidable.

2024-03-04 15:33 UTC, samwho commented on packages/types/src/api/web/application.ts
> +  file?: any
Looking at the place this is used, could this be `file?: { path: string }`?

2024-03-04 15:33 UTC, samwho commented on packages/server/src/api/controllers/application.ts
> +export async function duplicateApp(ctx: UserCtx) {
Could you add request and response types to `UserCtx` here?

2024-03-04 15:33 UTC, samwho commented on packages/server/src/tests/utilities/TestConfiguration.ts
> +  }
We're in the process of migrating out API calls from the `TestConfiguration` class and into the relevant API classes under `packages/server/src/tests/utilities/api`. Could you move this into the `ApplicationAPI` class, please? 🙏

2024-03-06 10:12 UTC, deanhannigan commented
Holding off on merging until this is merged in: https://github.com/Budibase/budibase/pull/13205

2024-03-06 11:12 UTC, samwho commented on packages/server/src/api/controllers/application.ts
> +    message: "app duplicated",
Is this field being added to the response to keep the type checker happy and make it such that you can assert agains this message in tests?

If it is, you can remove it and instead use the `Expectations.body` field in your test API calls (you've used `Expectations.status` to assert non-200 statuses in some tests) to assert the contents of an error response without having to pollute the successful type.

2024-03-12 14:51 UTC, MihailHadzhiev2022 approved these changes
LGTM

2024-03-13 10:10 UTC, samwho approved these changes
Looking good from my perspective! 🚀

2024-03-13 10:27 UTC, aptkingston approved these changes

2024-03-15 10:56 UTC, merged