Fix user access roles from displaying business
Budibase/budibase pull request #14368
Opened 2024-08-13 10:30 UTC by ConorWebb96

## Description
Changed business label to premium whenever the user doesn't have the correct permissions.

## Screenshots
<img width="408" alt="Screenshot 2024-08-13 at 11 29 05" src="https://github.com/user-attachments/assets/4c082365-92ea-4b43-8deb-bd0af8f857d8">

## Launchcontrol
Minor fix to UI. Access was showing business whenever user didn't have a high subscription tier. Should be showing premium.

2024-08-13 11:40 UTC, ConorWebb96 commented
Saw a thread as well as checked the pricing page and this is actually an enterprise tier feature. Updated UI, added some additional if statements to reflect this.

## Premium
<img width="1069" alt="Screenshot 2024-08-13 at 12 20 10" src="https://github.com/user-attachments/assets/866fe159-2bd2-4073-bebc-6604da86ec2f">

## UI
<img width="414" alt="Screenshot 2024-08-13 at 12 20 54" src="https://github.com/user-attachments/assets/0ca9c166-5d75-4a0c-8ee9-c11014aafdbe">

## Enterprise
<img width="1056" alt="Screenshot 2024-08-13 at 12 38 46" src="https://github.com/user-attachments/assets/5dbeffc2-1c4e-4b8f-a30c-006f65640cf0">

## UI
<img width="404" alt="Screenshot 2024-08-13 at 12 38 33" src="https://github.com/user-attachments/assets/09af2d59-740d-437e-bc1e-0044fdb44a28">

2024-08-13 12:17 UTC, melohagan requested changes

2024-08-13 12:17 UTC, melohagan commented on packages/builder/src/components/common/RoleSelect.svelte
> +  const subType = $licensing.license.plan.type
NAB: Just double check there's no null-pointer risk here

2024-08-13 12:17 UTC, melohagan commented on packages/builder/src/components/common/RoleSelect.svelte
> +      subType === Constants.PlanType.ENTERPRISE_BASIC
I think you need to account for `ENTERPRISE_BASIC_TRIAL` as well

2024-08-13 12:17 UTC, melohagan commented on packages/builder/src/components/common/RoleSelect.svelte
> +            ? null
Same as above `ENTERPRISE_BASIC_TRIAL`

2024-08-13 12:17 UTC, melohagan commented on packages/builder/src/components/common/RoleSelect.svelte
> +          (subType === Constants.PlanType.ENTERPRISE_BASIC_TRIAL &&
This time you need `ENTERPRISE_BASIC` as well? And why is ENTERPRISE_BASIC_TRIAL and `perAppBuildersEnabled` grouped together here?

2024-08-13 12:17 UTC, melohagan commented on packages/builder/src/components/common/RoleSelect.svelte
> +          subType === Constants.PlanType.ENTERPRISE ||
Same as above - could this duplicate code be moved into a shared function?

2024-09-11 08:48 UTC, shogunpurple requested changes
Just need to update enterprise basic trial key and it should be good to merge

2024-09-11 09:01 UTC, ConorWebb96 commented on packages/builder/src/components/common/RoleSelect.svelte
> +      subType === Constants.PlanType.ENTERPRISE_BASIC_trial
Cheers and fixed 👍

2024-09-11 09:09 UTC, shogunpurple approved these changes
LGTM

2024-09-12 15:53 UTC, merged