New data UI
Budibase/budibase pull request #14442
Opened 2024-08-23 13:25 UTC by aptkingston

## Description
This PR is a large refactor of how the data UI functions - making views a first class citizen and relating everything in Budibase back to data.

Designs: https://www.figma.com/board/kj4VXQQLcls3cemiFceZP8/3.0?node-id=54-10194&t=uNzp8ox3Wo8zBUJN-0

Views are now displayed horizontally in a new bar
![image](https://github.com/user-attachments/assets/63bdd5ea-1751-4c83-8b3d-e34674976718)
![image](https://github.com/user-attachments/assets/c020423e-4f4d-443b-8115-9ac22991b18c)

Old views will also appear here, and render the old view UI as always. The only change is the removal of the title, as this is redundant. An old view for example:
![image](https://github.com/user-attachments/assets/bf110540-a4bc-4de1-ac18-8bb5ab4bfef9)

Overflowed views are handled by a dropdown menu, which has a nested menu to support editing or deleting them as well:
![image](https://github.com/user-attachments/assets/949d9b0d-f392-4120-927f-ea0895398f5c)

Views are created inline instead of in a modal:
![image](https://github.com/user-attachments/assets/e0a31089-e906-4518-8536-c418fccc07d1)

Row actions are available for both tables and views. They can be toggled on and off for views:
![image](https://github.com/user-attachments/assets/65fc0f11-a709-473e-b870-1e560d8c5c51)
![image](https://github.com/user-attachments/assets/015acc5e-b086-4e4c-afaf-9d7c283d03ea)

Automations which use the selected table as their trigger are now shown via a new button. This is not available on views as views cannot be used in automations.
![image](https://github.com/user-attachments/assets/60efd357-dd1f-4096-8908-ba18a73def26)

Screens which use the selected table or view (anywhere at all - it searches for the ID in the entire screen) are shown via a new button. This is available on both tables and views:
![image](https://github.com/user-attachments/assets/1b5b6007-f5c2-429c-8c53-5deee804e145)

Screens and automations can be generated for the selected table or view. Tables support both, views only support screens. Creating an automation will instantly create it and auto-name it. Creating a screen will skip most of the screen creation wizard and only ask you for the final decision - what type of table/form screen do you want:
![image](https://github.com/user-attachments/assets/8358b119-e472-4655-9535-90180873e95b)
![image](https://github.com/user-attachments/assets/4bd1c140-c76e-4836-9449-3ae88cb2accf)
![image](https://github.com/user-attachments/assets/4210d8db-b605-4941-99eb-2d1e9562acbf)

Access is still available as-is for both tables and views, and will be redesigned in an upcoming ticket. The only change is that editing custom roles is now available everywhere you can see access, rather than only hidden inside the users table:
![image](https://github.com/user-attachments/assets/8cbb9ffa-61f3-4946-ad8c-31b54b3deaea)

Automations are now grouped by trigger table first, then grouped by trigger type for all other automations:
![image](https://github.com/user-attachments/assets/8b508f14-04f1-448d-9de7-59d4524c23ba)

Row actions can be deleted or renamed via their automations:
![image](https://github.com/user-attachments/assets/4fdfa5d7-5173-4cf4-b20c-2c02f5fedf7a)

Auto generated automations no longer are prefixed by the table name. Automation autonaming has been improved and will generate sequential non-clashing names.

## Row action usage
When in the data section, row actions are available using a new actions dropdown button. Opening the action dropdown for a row will also highlight that row so that you know which row the actions are targeting (help for wide rows):
![image](https://github.com/user-attachments/assets/73cdd28c-2dc2-4d51-b00e-c0dd0d2434da)

Rows are refreshed after actions execute, so here's a quick example of approving a request:

https://github.com/user-attachments/assets/d6d0900a-4ae6-4f84-91a3-d60da93f3a2f

In apps, row actions can be triggered using the new "row action" button action. This allows you to pick the table/view, row ID and row action to run. This also includes parameters for requiring confirmation:
![image](https://github.com/user-attachments/assets/6ab36690-9045-4083-8b95-ea6fd4100e73)

## Collapsed button groups
As seen in data section row actions, buttons can now be collapsed into a single dropdown. This is now available:
- In data section row actions
- In button group components
- When adding buttons to tables
- When adding buttons to form blocks and multi step form blocks

![image](https://github.com/user-attachments/assets/287b8b63-1dde-4954-9a2f-1a4654303b7e)
![image](https://github.com/user-attachments/assets/3a2e37d9-ca44-4f3e-b3df-b2bd8701798c)
![image](https://github.com/user-attachments/assets/40fdc30b-8c88-4eec-9077-77020facb193)
![image](https://github.com/user-attachments/assets/6d89ab8a-c98d-4adc-ae3b-59d305f1ac0f)

## Row action button templates
Row actions are available as button templates, to save time when building your UI. When adding buttons to tables or form blocks, you'll see a new dropdown menu when adding buttons (if your datasource has any row actions). This dropdown will let you instantly create a fully configured button to run your row action with a single click:
![image](https://github.com/user-attachments/assets/ba2334ad-8e09-4a49-b2f4-2d4c36a1d0f3)

You can create a custom button as always using the "Custom button" option. If you don't have any row actions on your datasource, a custom button will be automatically created.

## Row actions in autoscreens
Creating any variant of a table or form autoscreen will now include row actions. They will be added to tables (in the case of inline table editing) or added to your forms (in the case of editing rows inside forms for table autoscreens or form autoscreens og the update variant).

If you have lots of row actions we will automatically collapse your button group into a dropdown to avoid having a huge list of buttons.

## Addresses
- https://linear.app/budibase/issue/BUDI-8570/make-views-part-of-the-core-flow
- https://linear.app/budibase/issue/BUDI-8432/button-action-for-row-actions
- Lots of other unticketed work, but described in https://linear.app/budibase/project/row-actions-2d0d3dff3761/overview

## Feature branch env
[Feature Branch Link](http://fb-new-data-ui.fb.qa.budibase.net)

2024-08-23 14:10 UTC, joebudi commented
Incredible work!

2024-09-04 10:10 UTC, aptkingston commented on packages/server/src/sdk/app/automations/utils.ts
> +      displayName: rowActionName,
Only backend change is removing the table name prefix from row action automation display names. This is no longer needed as we now group them by datasource.

2024-09-10 23:08 UTC, deanhannigan requested changes
Amazing work @aptkingston! So many QoL updates jammed into one PR! 🚀 

The data section is really solid and given the scale of the changes, in general, I saw only a few minor bugs:

- `BUG` - screen and automations buttons present in the `User` section header
    - They don't do anything but should be removed
- `BUG` - Access Roles revert in the data section UI when the popover is closed and reopened
    - The underlying permission HAS been changed, it just resets to the previous value.
    - This happens in both the table and view screens in the data section
- `BUG` - filtering on Google Sheets views, saves but does nothing? I'm not 100% sure that this is related to your changes.

2024-09-10 23:13 UTC, deanhannigan commented on packages/bbui/src/ButtonGroup/CollapsedButtonGroup.svelte
The MVP of the entire PR 👏

2024-09-11 07:51 UTC, aptkingston commented
Appreciate the review!

> BUG - screen and automations buttons present in the User section header
They don't do anything but should be removed

Nice one, yep I deliberately removed the generate button for the users table, but forgot to remove these. Fixed.

> BUG - Access Roles revert in the data section UI when the popover is closed and reopened
The underlying permission HAS been changed, it just resets to the previous value.
This happens in both the table and view screens in the data section

You're right, but I think actually I'll leave this as it's being completely rewritten in my next PR - and none of this will be shipped until that work is done too.

> BUG - filtering on Google Sheets views, saves but does nothing? I'm not 100% sure that this is related to your changes.

99.9% sure this is nothing to do with my changes... I hope anyway!

2024-09-11 07:52 UTC, aptkingston commented on packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/_components/CreateViewModal.svelte
Nope! It's also completely empty haha. Removed.

2024-09-11 08:06 UTC, deanhannigan approved these changes
LGTM!

2024-09-11 08:24 UTC, merged