Clear form action
Budibase/budibase pull request #2114
Opened 2021-07-26 13:08 UTC by mslourens

## Description
Add the `Clear Form` action to the button actions. Clicking this button will clear the form.  I used the ValidateForm as an example how to create new actions for forms. 

## Screenshots
![image](https://user-images.githubusercontent.com/1907152/126993758-717dbfc2-28d1-4a86-b2ba-be47a1d81d67.png)

2021-07-26 14:25 UTC, aptkingston requested changes
Thanks so much for the contribution @mslourens! This is pretty much perfect to merge as it is, but I've just spotted a couple of tiny things which would be good to address before merging. Awesome work! 👍

2021-07-26 14:25 UTC, aptkingston commented on packages/standard-components/src/forms/InnerForm.svelte
> +      const { fieldState } = fieldMap[field]
I would maybe declare a new variable here for the value we're going to revert to, to save duplication down below. We need to check if there's an initial value here, so something like:
`const newValue = initialValues[field] ?? defaultValue`

2021-07-26 14:25 UTC, aptkingston commented on packages/standard-components/src/forms/InnerForm.svelte
> +        state.value = defaultValue
Using the new variable declared above, we can update this to:
`state.value = newValue`
to accound for initial values and default values.

2021-07-26 14:25 UTC, aptkingston commented on packages/standard-components/src/forms/InnerForm.svelte
> +        state.values = { ...state.values, [field]: defaultValue }
Using the new variable declared above, we can update this to:
`state.values = { ...state.values, [field]: newValue }`
to accound for initial values and default values.

2021-07-26 14:25 UTC, aptkingston commented on packages/standard-components/src/forms/InnerForm.svelte
> +      return true
We don't need to return anything here since we never need the result of this function, we could just remove this line.

2021-07-26 14:27 UTC, aptkingston commented
Those test failures just look like random failures, so I've ran them again for you. Should pass this time!

2021-07-26 15:13 UTC, aptkingston approved these changes
Looks good to me 👍

2021-07-27 08:41 UTC, joebudi commented
@all-contributors please add @mslourens for tests and code

2021-07-28 09:42 UTC, merged