replace spaces with underscores in screen routes
Budibase/budibase pull request #2147
Opened 2021-07-28 07:10 UTC by mslourens

## Description
Fixes #2146: replace spaces in screen route input fields with underscores to prevent breaking routes

2021-07-28 13:53 UTC, mslourens commented
the build fails for no particular reason, locally all Cypress tests succeed. I am not allowed to re-run the tests, so if one of you guys could do that, that would be awesome.

2021-07-28 14:07 UTC, Rory-Powell commented
@mslourens kicked them off again

2021-08-05 15:26 UTC, shogunpurple requested changes
Hi @mslourens thanks again for the contribution. I had a chat with the team and right now we use dashes for auto screen routes generated from tables with a space. If we change from underscores to dashes in this PR to keep things consistent, I'll get it merged!

2021-08-05 16:31 UTC, shogunpurple commented
Also @mslourens I would just like to say a huge thank you from the team for your contributions to the project.

You have provided an immense amount of value in such a short time! We would like to invite you to our discord channel, where we have a chat for contributors.

https://discord.gg/xSQnaypz

We would also love to hear more about your use case with budibase as well understand any way we can help you out.

2021-08-06 09:40 UTC, shogunpurple commented on packages/builder/cypress/integration/createScreen.js
> +      cy.contains("/test_with_spaces").should("exist")
@mslourens looks like the cypress tests are failing due to the switch to dashes. Update this to:

```
test-with-spaces
```

and we are good to go.

2021-08-06 20:42 UTC, merged