WIP: Frontend Section Bugfixes #387
Budibase/budibase pull request #390
Opened 2020-06-25 16:49 UTC by mjashanks

#387

2020-06-25 17:44 UTC, shogunpurple commented on packages/builder/src/builderStore/store/backend.js
> +          model =
Should we just:

A) Always pass a modelId to this function
B) Always pass a model object to this function

2020-06-27 10:09 UTC, shogunpurple requested changes
We are reimplementing default browser behaviour through regex, parsing and mapping of CSS strings here. Have a look at this excerpt from the W3 spec:

![Screenshot 2020-06-27 at 10 51 59](https://user-images.githubusercontent.com/11256663/85919572-3bef4b80-b864-11ea-8bc5-5cf24afc40c2.png)

The browser is smart about what it actually does download. When the browser performs the layout step and builds its render tree, it knows which fonts are used on the page, and will only fetch the ones that are required. Have a look at this as well - https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization

In any case, I think we can just inject the `link` tags we need (the ones in the components, etc) into the head of the document, and we can allow people to add more fonts in future by pasting link tags into the builder, or allowing them to select one from google fonts which will then be added as further `link` tags to their apps `head`.

2020-06-27 19:19 UTC, mjashanks commented
Thats really great to know, I had no idea :/

2020-06-29 13:33 UTC, mjashanks commented
Reopening in another PR, as a --force pushed and this PR doesnt seem to pick that up

2020-06-29 13:33 UTC, closed without merging