Further redis TS conversion
Budibase/budibase pull request #7176
Opened 2022-08-09 12:50 UTC by Rory-Powell

## Description
- Add additional TS conversions for redis
- Add `ioredis` types and integrate with `RedisWrapper`

2022-08-11 07:51 UTC, Rory-Powell reviewed
@mike12345567 the only change I'm concerned about in this one is the rename of `delete` to `deleteKey` in `cache/generic`. This had to be done as `delete` is a restricted function name. I think I've covered the usages but I'm not 100% sure, would be grateful if you could take a quick look to make sure there aren't any missed ones

2022-08-11 11:03 UTC, mike12345567 commented on packages/backend-core/src/cache/generic.ts
> +export const CacheKeys = {
Could possibly convert this and the TTL into real TS enums.

2022-08-11 11:03 UTC, mike12345567 approved these changes
LGTM!

2022-08-11 11:08 UTC, mike12345567 requested changes
Actually - had a think about the `deleteKey` changes - this will be a pretty huge change as the redis clients are returned from the `init` file and used all over the place.

For example have a look at `packages/backend-core/src/cache/user.js` - line 61 has a cache delete using the `redis.getUserClient()` function. Not sure how to account for this - changing usage of this could be quite difficult.

2022-11-29 11:32 UTC, mike12345567 commented
Closing as superseded by complete typescript refactor.

2022-11-29 11:32 UTC, closed without merging