Feature/add details button custom renderer for grid component
Budibase/budibase pull request #734
Opened 2020-10-15 18:13 UTC by kevmodrome

## Description
Adds a details column to the grid component that links to the detail view. App builder needs to enter a url that is prepended to the id.

## Screenshots
https://cln.sh/fD4u5B

2020-10-15 18:51 UTC, joebudi commented
@kevmodrome maybe make the icon var(--grey-6) to match the relationship tabs? If you feel blue is better, try var(--blue).

2020-10-15 18:57 UTC, kevmodrome commented
Nah, whichever works for me! It was just blue because that's the link color, I changed it to the grey you suggested

2020-10-15 20:51 UTC, aptkingston requested changes
Nice work! 👌 Just maybe change the control over like I noted above.

2020-10-15 20:51 UTC, aptkingston commented on packages/builder/src/components/userInterface/temporaryPanelStructure.js
> +                control: Input,
We actually have the `ScreenSelect` control made specifically for selecting screens to link to - that's what's used for choosing the target of a `Link` or a `Card` for example. Might be a good idea to use that here to make it easier for people to pick the right URL.

2020-10-16 08:38 UTC, aptkingston approved these changes

2020-10-16 08:51 UTC, merged