Render groupBy array options as tags
Budibase/budibase pull request #8764
Opened 2022-11-22 10:00 UTC by deanhannigan

## Description

When applying a `Group by` option to a view using an array field type, the options will display in the `Group` field as a string.

## Screenshots

The view below calculates a total for the `Cost` column and groups by `Expense Tags`. The options display as a string

<img src="https://user-images.githubusercontent.com/5913006/203282261-bd553062-5e86-444a-ad80-54107cae20da.png" width="600"/>

After passing an updated table schema, the array options display as tags.

<img src="https://user-images.githubusercontent.com/5913006/203282250-c07b650d-c6b6-4251-b7b7-1dcac8c80f12.png" width="600"/>

2022-12-16 10:17 UTC, melohagan requested changes
Hey @deanhannigan 

I pulled this down and had a play around - looks great; much nicer!

I did notice some issues with the filtering in the **Design** section though. (Although I think the filtering of a view in the design section may not be working at the moment, it would be good to fix if possible.)

*My view*
![Screenshot 2022-12-16 at 10 11 42](https://user-images.githubusercontent.com/101575380/208075616-882f4f29-5a12-4210-b9c2-c5bf576a8585.png)

*No options in the dropdown within the Design section*
![Screenshot 2022-12-16 at 10 12 38](https://user-images.githubusercontent.com/101575380/208075771-7b0317a9-6853-4436-8770-d07d7ebb1d07.png)

*If I just use the table without the view:*
![Screenshot 2022-12-16 at 10 16 06](https://user-images.githubusercontent.com/101575380/208076384-4a277c08-b82c-4f33-9a06-7816a90a17ce.png)

Also there is this issue too, which is somewhat related to this work: https://github.com/Budibase/budibase/issues/8964
But if it's scope creep, that's fine.

2023-01-03 11:23 UTC, deanhannigan commented
Hi @melohagan, as you mentioned above regarding the view filtering, this is a separate issue with the filtering of a grouped view in the Designer. Definitely create a separate issue for it. The above info and screenshots are perfect!

2023-01-03 11:29 UTC, melohagan approved these changes

2023-01-10 16:25 UTC, shogunpurple approved these changes
LGTM!

2023-01-10 16:25 UTC, merged