Trigger automation action
Budibase/budibase pull request #981
Opened 2021-01-11 10:01 UTC by mjashanks

## Description

#949 

Changes
1. When creating a new automation, we now have an "App Action" trigger. This allows the manual building of the input schema.
2. For button click "Define Actions", we have a new option, called "Trigger Automation", which allows selecting of automations that have the "App Action" trigger type. We can then data-bind, to build up the schema declared in No. 1 above
3. The client library handles this new "Trigger Automation" type.

## Screenshots
https://www.loom.com/share/a8abec4b22a249eb937df2fbc3613e8b

2021-01-11 10:04 UTC, joebudi commented
@mjashanks the input style for the automation item is not consistent with the rest of the inputs. (It's white, the others are grey).

2021-01-11 10:08 UTC, mjashanks commented
> @mjashanks the input style for the automation item is not consistent with the rest of the inputs. (It's white, the others are grey).

@joebudi do you mean the outlined one, where we type into to add fields? Will update that.

![image](https://user-images.githubusercontent.com/3524181/104167737-c5c3c800-53f4-11eb-94af-2faaff44f7b8.png)

How do you feel about these?

![image](https://user-images.githubusercontent.com/3524181/104167788-db38f200-53f4-11eb-94ee-d1d973a50114.png)

I realise that they are very different from other inputs. We are short on space here, which is why I opted for a plain, squared-off input.

2021-01-11 10:53 UTC, shogunpurple requested changes
Mainly stylistic things, but I think we need to rethink the design/styling of the schema builder inputs before we merge this.

2021-01-11 10:53 UTC, shogunpurple commented on packages/server/src/automations/triggers.js
> +  APP: {
should we just call this `AUTOMATION_TRIGGER`? App action seems quite generic

2021-01-11 10:53 UTC, shogunpurple commented on packages/builder/src/components/userInterface/EventsEditor/actions/TriggerAutomation.svelte
> +    .filter(a => a.definition.trigger && a.definition.trigger.stepId === "APP")
NAB: should be able to just do: `a.definition.trigger?.stepId === "APP"`

2021-01-11 10:53 UTC, shogunpurple commented on packages/client/src/utils/buttonActions.js
> +  for (let field in action.parameters.fields) {
I think you might be able use the `enrichDataBindings` helper here to parse all your values without looping.

2021-01-11 10:53 UTC, shogunpurple commented on packages/server/src/automations/triggers.js
> +      // values are likely to be submitted as strings, so we shall convert to correct type
Should we just convert them before sending?

2021-01-11 10:53 UTC, shogunpurple commented on packages/builder/src/components/automation/SetupPanel/SchemaSetup.svelte
> +  $: fieldsArray = Object.entries(value).map(([name, type]) => ({
NAB: I think you might save yourself a lot of pain here if you just dealt with the array the whole time, used `bind`, and construct/reduce the schema object from the array when the actual action gets executed.

2021-01-12 14:58 UTC, mjashanks commented
> I think you might be able use the enrichDataBindings helper here to parse all your values without looping.

i cannot, as the fields object is a `{ "key" : { ... } }`. enrichBindings expects a `{ "key": "string" }`

> Should we just convert them before sending?

The issue with this is that we need to then know the type on the client app, and the type can be changed in trigger setup. At the moment, we need to be able to change the type, as all fields default to `string`, when creating an automation via a button click.

> I think you might save yourself a lot of pain here if you just dealt with the array the whole time, used bind, and construct/reduce the schema object from the array when the actual action gets executed.

I think you're right. However, I am reusing the `SaveFields` control, which is also used by the `Save Row` action. I don't want to have to go changing that as well.

Other changes adressed

2021-01-12 15:05 UTC, shogunpurple approved these changes

2021-01-13 10:24 UTC, mjashanks commented
Demo of creating an automation from button actions, and some styling changes to the schema setup, designed by @joebudi:

https://www.loom.com/share/2d4175c0e1bd4659bb51f7cf8cfe8d60

2021-01-13 10:36 UTC, joebudi commented
> Demo of creating an automation from button actions, and some styling changes to the schema setup, designed by @joebudi:
> 
> 
> https://www.loom.com/share/2d4175c0e1bd4659bb51f7cf8cfe8d60

I was semi-expecting the add button to open a popover. I'm not sure how the user would know to type the title of the new field or dropdown the string - I feel these need indicators. What do you think?

2021-01-13 10:44 UTC, mjashanks commented
> I was semi-expecting the add button to open a popover.

Yes, it would be better, although I think the user would work out what they are supposed to do.  

How would you expect the user to edit an existing field? delete and re-add? At the moment, they can just into the fields.

Happy to add a popover, although I will not be getting back to this until Friday at the earliest.

2021-01-13 10:45 UTC, joebudi commented
> > I was semi-expecting the add button to open a popover.
> 
> Yes, it would be better, although I think the user would work out what they are supposed to do.
> 
> How would you expect the user to edit an existing field? delete and re-add? At the moment, they can type into the fields.
> 
> Happy to add a popover, although I will not be getting back to this until Friday at the earliest.

Can you add a title placeholder? and maybe a dropdown arrow? That would go a long way IMO.

2021-01-13 10:56 UTC, mjashanks commented
@joebudi hows this?

![image](https://user-images.githubusercontent.com/3524181/104443077-d9eefd00-558d-11eb-8256-020f41ded005.png)

2021-01-13 10:57 UTC, joebudi commented
> @joebudi hows this?
> 
> ![image](https://user-images.githubusercontent.com/3524181/104443077-d9eefd00-558d-11eb-8256-020f41ded005.png)

Bingo. Incredible work Mike. What does it look like in dark mode?

2021-01-13 10:57 UTC, mjashanks commented
![image](https://user-images.githubusercontent.com/3524181/104443309-30f4d200-558e-11eb-96a5-64afde22997f.png)

2021-01-13 10:58 UTC, joebudi commented
Chef's kiss

2021-01-13 11:02 UTC, mjashanks commented
@shogunpurple there have been a few changes since you reviewed. Let me know if you are still happy :)

2021-01-13 11:05 UTC, shogunpurple commented
yep! LGTM

2021-01-13 11:06 UTC, merged